services:
  - type: web
    name: multi-agent-portfolio-analysis
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.headless true --server.port $PORT --server.address 0.0.0.0
    healthCheckPath: /
    envVars:
      - key: XAI_API_KEY
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: TO_EMAIL
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
        value: "200"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: "false"
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: portfolio-analysis-disk
      size: 1GB
      mount: /opt/render/project/data
    autoDeploy: true
    branch: main

  - type: redis
    name: portfolio-analysis-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru

  - type: pserv
    name: portfolio-analysis-db
    plan: starter
    region: oregon
    databaseName: portfolio_analysis
    databaseUser: portfolio_user 