[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
caching = true
displayEnabled = true
showErrorDetails = false

[logger]
level = "info"
enableLogging = true

[global]
developmentMode = false
logLevel = "info"
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[mapbox]
token = ""

[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false 