# Streamlit Community Cloud Secrets Configuration
# Copy this file and fill in your actual values
# Add these secrets in your Streamlit Cloud app settings

[general]
# xAI Grok API Configuration
XAI_API_KEY = "your_xai_api_key_here"

# Email Configuration (for notifications)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SENDER_EMAIL = "your_email@gmail.com"
SENDER_PASSWORD = "your_gmail_app_password"
TO_EMAIL = "recipient@example.com"

# Database Configuration (for production)
DATABASE_URL = "postgresql://user:password@host:port/database"

# Application Configuration
ENVIRONMENT = "production"
DEBUG = "false"

# Redis Configuration (migrated to Supabase)
# REDIS_URL = "redis://localhost:6379"

# API Configuration
API_TIMEOUT = "30"
MAX_RETRIES = "3"
CACHE_TTL = "3600"

# Portfolio Configuration
DEFAULT_PORTFOLIO = "AAPL,GOOGL,MSFT,TSLA,AMZN"
ANALYSIS_INTERVAL = "3600"
MAX_TICKERS = "20"

# Notifications Configuration
EMAIL_ENABLED = "true"
HIGH_VOLATILITY_THRESHOLD = "0.05"
MEDIUM_VOLATILITY_THRESHOLD = "0.02"

# Feature Flags
ENABLE_BACKGROUND_ANALYSIS = "true"
ENABLE_KNOWLEDGE_EVOLUTION = "true"
ENABLE_EMAIL_NOTIFICATIONS = "true"
ENABLE_CACHING = "true" 